platform=Android
username=oauth-sadginayak.15-1b0c5
accesskey=7d084c3c-f21a-4856-a61d-2856caf6f6ad
sauceURL=https://ondemand.eu-central-1.saucelabs.com:443/wd/hub
# For Sauce, deviceName can be generic
deviceName=Android GoogleAPI Emulator
platformVersion=12
appPath=src/test/resources/apps/monefy.apk